SPHTech-Platform/terraform-aws-eks

node_groups.tf
Changed cluster_name value on the node_group.tf file.
=> changed cluster_name value in node_group.tf

README.md, variables.tf
- Also bump default cluster version to 1.22
=> [Breaking] Manage AWS Auth configmap contents by default

modules/self_managed_nodes/main.tf
Adding asg tags for spot labels
=> Add asg tags for spot instances.

modules/essentials/README.md, modules/essentials/storageclass.tf, modules/essentials/variables.tf, modules/essentials/versions.tf
To-do
- configure kubectl provider
=> Remove usage of `kubectl` provisioner

modules/eks_managed_nodes/asg_tags.tf, modules/eks_managed_nodes/data.tf, modules/eks_managed_nodes/outputs.tf
- use node_groups subnet
- Remove unnecessary data
=> Remove unnecessary dependency for ASG tags

modules/essentials/versions.tf
@niroz89 we release this as 0.7.0 and https://github.com/SPHTech-Platform/terraform-aws-eks/pull/33 as 0.6.1 ?
=> [Breaking] Remove experimental feature as it is released in 1.3

README.md, main.tf, node_groups.tf, versions.tf
* Fix sub module dependency
* Remove duplicate security group rule (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0e3cb9a0afcea87e1da0c87ecc969ffb963619ea/node_groups.tf#L137)
=> Fix dependency issue on v19

modules/essentials/fluent_bit.tf
=> Fix odic provider name for fluentbit

fargate_profile.tf, main.tf, node_groups.tf
[PFMENG-924]
[PFMENG-924]: https://sph.atlassian.net/browse/PFMENG-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Essentials namepsace to fargate selector and refactor files

modules/essentials/README.md, modules/essentials/fluent_bit.tf, modules/essentials/variables.tf
https://github.com/cert-manager/cert-manager/issues/3237
=> Use 10260 instead of 10250 due the same port used by kubelet in fargate

main.tf, modules/eks_managed_nodes/asg_tags.tf
- propagate asg tags
- correct description for ingress rule
=> Propagate asg tags

karpenter.tf, modules/karpenter/karpenter.tf, modules/karpenter/templates/nodetemplate.tftpl
fix the http hop to resolve SCP issue
=> fix the http hop to resolve SCP issue 

variables.tf
fix variable to include metadataoption
=> fix variable to include metadataoption

modules/essentials/fluent_bit.tf, modules/essentials/templates/fluent_bit.yaml, modules/essentials/variables.tf
[PFMENG-2991] - Adding Option to Customize the Toleration of Fluentbit
[PFMENG-2991]: https://sph.atlassian.net/browse/PFMENG-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PFMENG-2991] - Adding Option to Customize the Toleration of Fluentbit

modules/essentials/fluent_bit.tf, modules/essentials/templates/fluent_bit.yaml
[PFMENG-2991] - Adding Affinity to the FluentBit to Ignore Fargate Nodes
[PFMENG-2991]: https://sph.atlassian.net/browse/PFMENG-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PFMENG-2991] - Adding Affinity to the FluentBit to Ignore Fargate Nodes

.pre-commit-config.yaml, modules/essentials/fluent_bit.tf, modules/essentials/templates/fluent_bit.yaml, modules/essentials/variables.tf
[PFMENG-3033] add exclude namespace for fluentbit logging
[PFMENG-3033]: https://sph.atlassian.net/browse/PFMENG-3033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PFMENG-3033] add exclude namespace for fluentbit logging

modules/essentials/templates/fluent_bit.yaml
- fix fluentbit config indentation
=> [PFMENG-3033] fix identation

modules/fargate_profile/fargate_logger.tf
enable k8 exclusion for fargate logger config
=> [PFMENG-3033] enable k8 exclusion for fargate logger

modules/essentials/data.tf, modules/essentials/fluent_bit.tf, modules/essentials/fluent_bit_s3.tf, modules/essentials/templates/fluent_bit.yaml, modules/essentials/variables.tf, modules/essentials/versions.tf
enable s3 as an output in fluentbit config
=> [PFMENG-3035] enable s3 as an output in fluentbit config

modules/essentials/data.tf, modules/essentials/fluent_bit.tf, modules/essentials/fluent_bit_s3.tf, modules/essentials/templates/fluent_bit.yaml, modules/essentials/variables.tf
add cw disable option in fluent-bit config
=> [PFMENG-3039] add cw disable option in fluent-bit config

modules/essentials/data.tf, modules/essentials/fluent_bit.tf
Refactor Fluentbit IAM Permission Module
=> Refactor Fluentbit IAM Permission Module
