main.tf, variables.tf
Modified the main.tf to add the below line 68 for the aws_auth creation. This argument was missing so it was not creating the aws-auth config file. Now i tested and its fixed.
create_aws_auth_configmap               = true
Please verify and approve.
=> Add Auth `ConfigMap` management variables

node_groups.tf, variables.tf
`default_group_name` already exists but not used.
introduced new variable `default_group_launch_template_name`.
=> Allow change name of default asg and launch template

modules/essentials/README.md, modules/essentials/storageclass.tf, modules/essentials/variables.tf
Supports using the default AWS key if unspecified
See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md
=> Support AWS Key encryption for CSI StorageClass 

README.md, iam.tf, main.tf, modules/eks_managed_nodes/README.md, modules/eks_managed_nodes/data.tf, modules/eks_managed_nodes/main.tf, modules/eks_managed_nodes/variables.tf, modules/essentials/README.md, modules/essentials/data.tf, modules/essentials/node_termination_handler.tf, modules/essentials/outputs.tf, modules/essentials/variables.tf, modules/self_managed_nodes/README.md, modules/self_managed_nodes/main.tf, node_groups.tf, outputs.tf, variables.tf
- Change core nodes to managed
- Cleanup outputs
- Disable node termination handler by default
=> [BREAKING] Switch default nodes to eks managed node groups.

variables.tf
Since version 0.6.0 we have switch to using EKS managed node groups by default which automatically creates a aws_auth configmap. Having `create_aws_auth_configmap=true` causes terraform plan to fail when creating a new cluster as the configmap already exists. Instead we should use `manage_aws_auth_configmap=true` that accepts the existing configmap into terraform state thereby bringing the configmap under terraform management.
=> Update create aws_auth configmap to false

node_groups.tf, policies.tf
Tflint interprets `var.subnet_ids` and `var.default_group_subnet_ids` as empty lists so when a `coalescelist` function is called on these `vars` it throws an error. A check has been added to avoid this issue.
=> fix: tflint coalescelist throws error when both lists are empty

modules/karpenter/karpenter.tf, modules/karpenter/variables.tf
Current default for bottlerocket is 
https://karpenter.sh/v0.27/concepts/node-templates/#bottlerocket
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
spec:
blockDeviceMappings:
- deviceName: /dev/xvda
ebs:
volumeSize: 4Gi
volumeType: gp3
encrypted: true
- deviceName: /dev/xvdb
ebs:
volumeSize: 20Gi
volumeType: gp3
encrypted: true
```
Which is insufficient for some workloads
=> Add block mappings to customize volume size

README.md, fargate_profile.tf, modules/fargate_profile/README.md, modules/fargate_profile/main.tf, modules/fargate_profile/variables.tf
Also fix fargate logger not having permissions to write logs to cloudtrail
=> Refactor fargate profile to only create securitygrouppolicy optionally, and create it part of fargate EKS cluster deployment

fargate_profile.tf, modules/essentials/README.md, modules/essentials/brupop.tf, modules/essentials/variables.tf
Bottlerocket update operator starts a controller deployment on one node, an agent daemon set on every Bottlerocket node, and an Update Operator API Server deployment. All components together collaborate to drive each Bottlerocket node through an update when updates are available.
Since the agent is a daemon set, it does not make sense to create fargate-profile for that. Daemonsets aren't supported on Fargate. 
Added option to disable brupop for fargate only clusters.
=> Add flag to disable bottlerocket update operator

.github/workflows/ci.yml, .tflint.hcl, fargate_profile.tf, main.tf
https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#security-groups-pods-deployment 
Requires ENABLE_POD_ENI to be set to true for SecurityGroupPolicy to be added to pods on managed nodes
=> Add condition and config values for enabling POD ENI

main.tf
Add ingress rule to `node_security_group` due to recent update in #69 
**Reference**
https://cert-manager.io/docs/installation/compatibility/
=> Add rule to node security group

main.tf
`aws eks describe-addon-configuration --addon-name vpc-cni --addon-version v1.13.2-eksbuild.1`
```
{
"$ref": "#/definitions/VpcCni",
"$schema": "http://json-schema.org/draft-06/schema#",
"definitions": {
"Affinity": {
"type": [
"object",
"null"
]
},
"EniConfig": {
"additionalProperties": false,
"properties": {
"create": {
"type": "boolean"
},
"region": {
"type": "string"
},
"subnets": {
"additionalProperties": {
"additionalProperties": false,
"properties": {
"id": {
"type": "string"
},
"securityGroups": {
"items": {
"type": "string"
},
"type": "array"
}
},
"required": [
"id"
],
"type": "object"
},
"minProperties": 1,
"type": "object"
}
},
"required": [
"create",
"region",
"subnets"
],
"type": "object"
},
"Env": {
"additionalProperties": false,
"properties": {
"ADDITIONAL_ENI_TAGS": { …
```
=> Add initEnv instead of Env to fix pod constantly restart issue

modules/fargate_profile/fargate_logger.tf
` Error: Failed to update Config Map: admission webhook "0500-amazon-eks-fargate-configmaps-admission.amazonaws.com" denied the request: Line is an invalid key/value pair, or a wrong directive. Line: log_stream_prefix `
=> Fix empty Fargate Stream Log Prefix

README.md, fargate_profile.tf, main.tf, modules/essentials/templates/fluent_bit.yaml, modules/fargate_profile/README.md, modules/fargate_profile/fargate_logger.tf, modules/fargate_profile/main.tf, modules/fargate_profile/variables.tf, variables.tf
- Manage IAM policy as part of fargate module
- Fix mixture of C and Golang plugin options
C plugin is `cloudwatch_logs`: https://docs.fluentbit.io/manual/v/1.5/pipeline/outputs/cloudwatch
Go plugin is `cloudwatch`: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit
=> Revamp Fargate Logging

modules/essentials/templates/fluent_bit.yaml
characters that can separate template variables- only dots and commas (`.` and `,`) can come after a template variable.
reference: https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch#limitations-of-record_accessor-syntax
=> fix syntax of fluent-bit output for cloudwatch

iam.tf, main.tf, variables.tf
feature request on this bug on provider repo: https://github.com/hashicorp/terraform-provider-aws/issues/38357
temporally disabling the pod identity association for EKS Addons, will use IRSA still this feature available
=> fix: Terraform aws provider still doesn't support pod identity associations for eks addons

karpenter.tf, main.tf, variables.tf
karpenter auto discover, security groups with matching tags, no need to pass the the SG Ids for NodeClass
=> feat: move karpenter secuity group selector from id to tags

variables.tf
- **Pod Identity is not supported** when using Fargate profiles.
- EBS Controller Pods running on Fargate profiles cannot leverage Pod Identity.
- If you plan to use **Pod Identity**, ensure that:
- EKS add-ons are **excluded from Fargate** profiles.
=> fix: pod identity for eks addons and nodeclass variable

modules/essentials/fluent_bit.tf, modules/essentials/templates/fluent_bit.yaml, modules/essentials/variables.tf
[PFMENG-2991] - Enable Option to Customize FluentBit Livess Probe and Readiness Probe
[PFMENG-2991]: https://sph.atlassian.net/browse/PFMENG-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PFMENG-2991] - Enable Option to Customize FluentBit Liveness Probe and Readiness Probe

modules/essentials/variables.tf
[PFMENG-2991] - Updating the Port Type of Fluentbit Readiness and Liveness Probe Variable
[PFMENG-2991]: https://sph.atlassian.net/browse/PFMENG-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PFMENG-2991] - Updating the Port Type of Fluentbit Readiness and Liveness Probe Variable

modules/essentials/fluent_bit.tf, modules/essentials/templates/fluent_bit.yaml, modules/essentials/variables.tf
- add custom parser variable 
- add k8 api endpoint variable 
- fix "kubernetes" filter
=> [PFMENG-3093] add custom parser variable
